import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import SupabaseProvider from "./providers/supabase/supabase-provider";
import { QueryProvider } from "./providers/tanstack-query/query-provider";
import { UserContextProvider } from "./providers/supabase/user-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <UserContextProvider>
            <QueryProvider>{children}</QueryProvider>
          </UserContextProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
